import type { Config, Field } from "./config.js";

const j = (v: unknown) => JSON.stringify(v);

function fieldChecks(fields: readonly Field[]): string {
  const lines: string[] = [];
  for (const f of fields) {
    const n = j(f.name);
    if (f.type === "email") {
      lines.push(`  const email = String(raw[${n}] ?? "").trim().toLowerCase();`);
      lines.push(`  if (!email || !/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email)) {`);
      lines.push(`    return reply(ctx, 400, { error: "A valid email address is required." });`);
      lines.push(`  }`);
      lines.push(`  record[${n}] = email;`);
      continue;
    }
    lines.push(`  {`);
    lines.push(`    const v = raw[${n}] == null ? "" : String(raw[${n}]).trim();`);
    if (f.required) {
      lines.push(`    if (!v) return reply(ctx, 400, { error: ${j(`${f.name} is required.`)} });`);
    }
    if (f.maxLength) {
      lines.push(`    if (v.length > ${f.maxLength}) {`);
      lines.push(`      return reply(ctx, 400, { error: ${j(`${f.name} is too long (max ${f.maxLength} characters).`)} });`);
      lines.push(`    }`);
    }
    if (f.type === "number") {
      lines.push(`    if (v && Number.isNaN(Number(v))) {`);
      lines.push(`      return reply(ctx, 400, { error: ${j(`${f.name} must be a number.`)} });`);
      lines.push(`    }`);
    }
    if (f.type === "url") {
      lines.push(`    if (v && !/^https?:\\/\\/\\S+$/.test(v)) {`);
      lines.push(`      return reply(ctx, 400, { error: ${j(`${f.name} must be a URL.`)} });`);
      lines.push(`    }`);
    }
    if (f.type === "choice") {
      lines.push(`    const allowed = ${j(f.options ?? [])};`);
      lines.push(`    if (v && !allowed.includes(v)) {`);
      lines.push(`      return reply(ctx, 400, { error: ${j(`${f.name} is not one of the allowed values.`)} });`);
      lines.push(`    }`);
    }
    lines.push(`    record[${n}] = v || null;`);
    lines.push(`  }`);
  }
  return lines.join("\n");
}

/** Generates the deployable Worker. Everything configurable is inlined, so the
 *  Worker reads no config at runtime and makes no extra KV reads to find it. */
export function buildWorker(c: Config): string {
  const ttl = c.retentionDays ? `, { expirationTtl: ${c.retentionDays * 86400} }` : "";
  const rl = c.rateLimit;

  return `// Generated by formkv — edit formkv.json and redeploy rather than editing here.
// Storage layout:
//   email:<address>  the signup record
//   rl:<ip>          rate-limit counter, expiring via TTL
//
// KV is eventually consistent. The duplicate check and the rate limit are both
// best-effort: simultaneous requests can each read stale state and both proceed.
// For a waitlist that is an acceptable trade. For anything that must not
// double-write, KV is the wrong store.

const ORIGINS = ${j(c.allowedOrigins)};
const HONEYPOT = ${j(c.honeypot)};
const MSG = ${j(c.messages)};
const SITE_URL = ${j(c.siteUrl)};
const SUPPORT_EMAIL = ${j(c.supportEmail)};

function cors(origin) {
  const base = {
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Vary": "Origin",
  };
  // Echo the origin only when it is allowed. Returning some other allowed origin
  // would still make the browser block the response, but it tells a stranger
  // which sites are on the list. Omitting the header blocks and says nothing.
  return ORIGINS.includes(origin)
    ? { "Access-Control-Allow-Origin": origin, ...base }
    : base;
}

const esc = (s) =>
  String(s).replace(/[&<>"]/g, (ch) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[ch]);

// A native form POST navigates to this response, so a person reads it. Serve a
// page. The fetch() path still gets JSON.
function page(status, payload, headers) {
  const ok = !payload.error;
  const title = ok
    ? (payload.status === "duplicate" ? "Already on the list" : "You're on the list")
    : "That didn't go through";
  return new Response(
    '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
      '<meta name="viewport" content="width=device-width,initial-scale=1">' +
      '<meta name="robots" content="noindex"><title>' + esc(title) + "</title><style>" +
      ":root{color-scheme:light dark}" +
      "body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;" +
      "background:Canvas;color:CanvasText;font:16px/1.55 ui-sans-serif,system-ui,sans-serif}" +
      "main{max-width:32rem}h1{font-size:clamp(24px,5vw,34px);letter-spacing:-.02em;margin:0 0 10px}" +
      "p{margin:0 0 22px;opacity:.75}a{display:inline-block;padding:10px 16px;border-radius:3px;" +
      "background:CanvasText;color:Canvas;text-decoration:none;font-size:14px}</style></head>" +
      "<body><main><h1>" + esc(title) + "</h1><p>" +
      esc(payload.message || payload.error) +
      (!ok && SUPPORT_EMAIL
        ? " You can also email <strong>" + esc(SUPPORT_EMAIL) +
          "</strong> and we'll add you by hand."
        : "") + "</p>" +
      (SITE_URL ? '<a href="' + esc(SITE_URL) + '">&larr; Back</a>' : "") +
      "</main></body></html>",
    { status, headers: { "Content-Type": "text/html; charset=utf-8", ...headers } },
  );
}

// headers is threaded through rather than held in a module variable: one isolate
// serves concurrent requests, so a mutable global would leak CORS across callers.
function reply(ctx, status, payload) {
  if (ctx.isForm) return page(status, payload, ctx.cors);
  return new Response(JSON.stringify(payload), {
    status,
    headers: { "Content-Type": "application/json", ...ctx.cors },
  });
}

${rl
      ? `const RL_MAX = ${rl.max};
const RL_WINDOW = ${rl.windowSeconds};

// Returns true when the request may proceed. Writes only when it does, so a
// client already over the limit costs no further writes.
async function underLimit(ip, env) {
  const key = "rl:" + ip;
  const stored = await env.FORM_KV.get(key);
  let count = 0;
  if (stored) {
    const d = JSON.parse(stored);
    if (Date.now() - d.t < RL_WINDOW * 1000) count = d.c;
  }
  if (count >= RL_MAX) return false;
  await env.FORM_KV.put(key, JSON.stringify({ t: Date.now(), c: count + 1 }), {
    expirationTtl: RL_WINDOW,
  });
  return true;
}`
      : "// Rate limiting disabled in formkv.json."}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin") || "";
    const corsHeaders = cors(origin);
    const ctx = { isForm: false, cors: corsHeaders };

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: corsHeaders });
    }
    if (request.method !== "POST") {
      return new Response("Method not allowed", { status: 405, headers: corsHeaders });
    }

    // Decided before any early return, so every response below — including the
    // rate-limit rejection — comes back in the shape the caller can read.
    const ct = request.headers.get("content-type") || "";
    ctx.isForm =
      ct.includes("application/x-www-form-urlencoded") || ct.includes("multipart/form-data");
    const isJson = ct.includes("application/json");
    if (!ctx.isForm && !isJson) {
      return reply(ctx, 415, { error: "Send JSON or a form post." });
    }

    try {
      // Parsed in its own try: a body the client mangled is a 400, not a 500.
      // Letting it fall to the outer handler would blame the server and log a
      // stack trace for what is ordinary bad input.
      let raw;
      try {
        raw = isJson
          ? await request.json()
          : Object.fromEntries(await request.formData());
      } catch {
        return reply(ctx, 400, { error: "Could not read that submission." });
      }
      if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
        return reply(ctx, 400, { error: "Malformed body." });
      }

      // Honeypot first: a caught bot costs zero KV operations, and is told it
      // succeeded so it does not learn the field is a trap.
      if (HONEYPOT && String(raw[HONEYPOT] ?? "")) {
        return reply(ctx, 200, { status: "ok", message: MSG.success });
      }

      // Validation before the rate limiter, so malformed spam burns no KV writes.
      // The daily write quota is the scarce resource here, not CPU.
      const record = {};
${fieldChecks(c.fields)}

${rl
      ? `      const ip = request.headers.get("cf-connecting-ip") || "unknown";
      if (!(await underLimit(ip, env))) {
        return reply(ctx, 429, { error: MSG.rateLimited });
      }`
      : ""}

      const key = "email:" + record.email;
      if (await env.FORM_KV.get(key)) {
        return reply(ctx, 200, { status: "duplicate", message: MSG.duplicate });
      }

      record.at = new Date().toISOString();
      await env.FORM_KV.put(key, JSON.stringify(record)${ttl});
      return reply(ctx, 201, { status: "ok", message: MSG.success });
    } catch (err) {
      console.error("formkv:", err && err.stack ? err.stack : err);
      return reply(ctx, 500, { error: "Something went wrong on our side." });
    }
  },
};
`;
}
